import Section from "./Section";
import Heading from "./Heading";
import { service1, service2, service3, check } from "../assets";
import { brainwaveServices, brainwaveServicesIcons } from "../constants";
import {
  PhotoChatMessage,
  Gradient,
} from "./design/Services";
import { motion } from "framer-motion";

const container = {
  hidden: {},
  show: {
    transition: {
      staggerChildren: 0.2,
      delayChildren: 0.1,
    },
  },
};

const item = {
  hidden: { opacity: 0, y: 40 },
  show: {
    opacity: 1,
    y: 0,
    transition: {
      duration: 0.5,
      ease: "easeOut",
    },
  },
};

const Services = () => {
  return (
    <Section id="how-to-use">
      <div className="container">

        <motion.div
          variants={item}
          initial="hidden"
          whileInView="show"
          viewport={{ once: true }}
        >
          <Heading
            title="Conversational AI made for your documents"
            text="NeuroVault unlocks the potential of your organization's knowledge base"
          />
        </motion.div>

        <div className="relative">

          <motion.div
            variants={item}
            initial="hidden"
            whileInView="show"
            viewport={{ once: true, amount: 0.3 }}
            className="relative z-1 flex items-center h-[39rem] mb-5 p-8 border border-n-1/10 rounded-3xl overflow-hidden lg:p-20 xl:h-[46rem]"
          >
            <div className="absolute top-0 left-0 w-full h-full pointer-events-none md:w-3/5 xl:w-auto">
              <img
                className="w-full h-full object-cover md:object-right"
                width={800}
                alt="AI Knowledge Base"
                height={730}
                src={service1}
              />
            </div>

            <div className="relative z-1 max-w-[17rem] ml-auto">
              <h4 className="h4 mb-4">Ask Your Documents</h4>
              <p className="body-2 mb-[3rem] text-n-3">
                NeuroVault lets your entire team query your private document
                library and get AI-generated answers with exact page citations
              </p>

              <motion.ul
                variants={container}
                initial="hidden"
                whileInView="show"
                viewport={{ once: true }}
                className="body-2"
              >
                {brainwaveServices.map((itemText, index) => (
                  <motion.li
                    key={index}
                    variants={item}
                    className="flex items-start py-4 border-t border-n-6"
                  >
                    <img width={24} height={24} src={check} />
                    <p className="ml-4">{itemText}</p>
                  </motion.li>
                ))}
              </motion.ul>
            </div>
          </motion.div>

         
          <motion.div
            variants={container}
            initial="hidden"
            whileInView="show"
            viewport={{ once: true, amount: 0.2 }}
            className="relative z-1 grid gap-5 lg:grid-cols-2"
          >

            <motion.div
              variants={item}
              className="relative min-h-[39rem] border border-n-1/10 rounded-3xl overflow-hidden"
            >
              <div className="absolute inset-0">
                <img
                  src={service2}
                  className="h-full w-full object-cover"
                  width={630}
                  height={750}
                  alt="Admin Approval Panel"
                />
              </div>

              <div className="absolute inset-0 flex flex-col justify-end p-8 bg-gradient-to-b from-n-8/0 to-n-8/90 lg:p-15">
                <h4 className="h4 mb-4">Admin Approval Workflow</h4>
                <p className="body-2 mb-[3rem] text-n-3">
                  Every document submitted by a member goes through an admin
                  approval queue — only verified content enters your knowledge
                  base.
                </p>
              </div>

              <PhotoChatMessage />
            </motion.div>

         
            <motion.div
              variants={item}
              className="p-4 bg-n-7 rounded-3xl overflow-hidden lg:min-h-[46rem]"
            >
              <div className="py-12 px-4 xl:px-8">
                <h4 className="h4 mb-4">Cited Answer Generation</h4>
                <p className="body-2 mb-[2rem] text-n-3">
                  Every answer generated by NeuroVault is traced back to the
                  exact source document and page number — no guessing, no
                  hallucinations.
                </p>
           
                <motion.ul
                  variants={container}
                  initial="hidden"
                  whileInView="show"
                  viewport={{ once: true }}
                  className="flex items-center justify-between"
                >
                  {brainwaveServicesIcons.map((icon, index) => (
                    <motion.li
                      key={index}
                      variants={item}
                      className={`rounded-2xl flex items-center justify-center ${
                        index === 2
                          ? "w-[3rem] h-[3rem] p-0.25 bg-conic-gradient md:w-[4.5rem] md:h-[4.5rem]"
                          : "flex w-10 h-10 bg-n-6 md:w-15 md:h-15"
                      }`}
                    >
                      <div
                        className={
                          index === 2
                            ? "flex items-center justify-center w-full h-full bg-n-7 rounded-[1rem]"
                            : ""
                        }
                      >
                        <img src={icon} width={24} height={24} alt={icon} />
                      </div>
                    </motion.li>
                  ))}
                </motion.ul>
              </div>

              <div className="relative h-[20rem] bg-n-8 rounded-xl overflow-hidden md:h-[25rem]">
                <img
                  src={service3}
                  className="w-full h-full object-cover"
                  width={520}
                  height={400}
                  alt="Knowledge Base Query"
                />
                <p className="absolute  right-[1rem] top-1 p-4 text-center text-n-3">
                  Cited Answers
                </p>
                 <p className="absolute  right-[1rem] top-[6rem] p-4 text-center text-n-3">
                  Knowledge Base Query
                </p>
                 <p className="absolute  right-[1rem] top-[13rem] p-4 text-center text-n-3">
                  Contextual Pinpointing data
                </p>
              </div>
            </motion.div>
          </motion.div>

          <Gradient />
        </div>
      </div>
    </Section>
  );
};

export default Services;